### ISSUE TITLE
[Feature]: make nullable fields easier

### ISSUE THREAD

**Issue by goenning** [PaddleHQ/paddle-go-sdk#16]
### Tell us about your feature request

```go
res, err := client.CreateDiscount(ctx, &paddlesdk.CreateDiscountRequest{
		Description:        "20% off",
		Type:               "percentage",
		Amount:             "20",
		Recur:              true,
		UsageLimit:         1,
		EnabledForCheckout: true,
		ExpiresAt:         time.Now().Add(48 * time.Hour).Format(time.RFC3339),
	})
```

The above doesn't work

### What problem are you looking to solve?

It should be easier to assign nullable values

### Additional context

AWS solves this with something like `aws.String("")` and `aws.Bool(true)`

### How important is this suggestion to you?

Nice to have

**Comment by mikeymike** [comment]
Hey @goenning 👋 ... thanks for raising this issue. I'll discuss this with the team and will update here with how we plan to tackle this 👍

**Comment by mikeymike** [comment]
@goenning It turns out I think we have added a helper for this already under `paddle.PtrTo` ... let me know if this helps I'll make sure we update our documentation to help highlight this

**Comment by goenning** [comment]
that worked! thanks
