### ISSUE TITLE
[Feature]: examples of handling webhook

### ISSUE THREAD

**Issue by goenning** [PaddleHQ/paddle-go-sdk#17]
### Tell us about your feature request

Would be useful to have examples/guides on how to handle webhook request instead of just the validator

### What problem are you looking to solve?

make it easier to adopt the sdk

### How important is this suggestion to you?

Nice to have

**Comment by goenning** [comment]
I eventually found the `paddlenotification` package.

In my usecase I handle all subscription operations on the same route, seems like it's safe to unmarshall the body into paddlenotification.SubscriptionUpdated regardless of what's the operation? They all seem to have the same body

**Comment by mikeymike** [comment]
Hey @goenning 👋 ... you're right this is something we could improve on to make it more clear. 

For Subscriptions most events do share the same `Data` type except for `SubscriptionCreated` so this _should_ be safe to do if you're use case isn't having to handle those.   

I'm going to keep the issue open until we have some better examples around this, thanks again for the report 👍

**Comment by Rusinas** [comment]
Yes, this is something that I'm looking for as well, would be so great to see some examples. Anyway, thanks for the package, it is awesome and right on time
