### ISSUE TITLE
[Bug]: Cannot use taxmode

### ISSUE THREAD

**Issue by page-fault-in-nonpaged-area** [PaddleHQ/paddle-go-sdk#25]
### What happened?

`cannot use paddle.TaxModeExternal (constant "external" of type "github.com/PaddleHQ/paddle-go-sdk".TaxMode) as *"github.com/PaddleHQ/paddle-go-sdk".TaxMode value in struct literalcompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#IncompatibleAssign)`

If I do

```
price, err := s.Client.CreatePrice(ctx, &paddle.CreatePriceRequest{
	ProductID: product.ID,
	UnitPrice: paddle.Money{
		Amount: strconv.Itoa(nxPrice.Price),
	},
	BillingCycle: &paddle.Duration{
		Interval:  paddle.IntervalMonth,
		Frequency: 1,
	},
	CustomData: map[string]interface{}{
		"internal_id": nxPrice.InternalID,
	},
	TaxMode: paddle.TaxModeExternal,
})
if err != nil {
	panic(err)
}
```

And if I do:

```
price, err := s.Client.CreatePrice(ctx, &paddle.CreatePriceRequest{
	ProductID: product.ID,
	UnitPrice: paddle.Money{
		Amount: strconv.Itoa(nxPrice.Price),
	},
	BillingCycle: &paddle.Duration{
		Interval:  paddle.IntervalMonth,
		Frequency: 1,
	},
	CustomData: map[string]interface{}{
		"internal_id": nxPrice.InternalID,
	},
	TaxMode: &paddle.TaxModeExternal,
})
if err != nil {
	panic(err)
}
```

`invalid operation: cannot take address of paddle.TaxModeExternal (constant "external" of type "github.com/PaddleHQ/paddle-go-sdk".TaxMode)compiler[UnaddressableOperand](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UnaddressableOperand)`

The SDK doesn't allow setting TaxMode on price. 

### Steps to reproduce

1.
2.
3.
...

### What did you expect to happen?

Allow TaxMode to accept `paddle.TaxModeExternal`

**Comment by page-fault-in-nonpaged-area** [comment]
```
taxMode := paddle.TaxModeExternal
for idxPr, nxPrice := range nxProduct.Prices {
        price, err := s.Client.CreatePrice(ctx, &paddle.CreatePriceRequest{
	        ProductID: product.ID,
	        UnitPrice: paddle.Money{
		        Amount: strconv.Itoa(nxPrice.Price),
	        },
	        BillingCycle: &paddle.Duration{
		        Interval:  paddle.IntervalMonth,
		        Frequency: 1,
	        },
	        CustomData: map[string]interface{}{
		        "internal_id": nxPrice.InternalID,
	        },
	        TaxMode: &taxMode,
        })
        if err != nil {
	        panic(err)
        }
```
turns out it only works like this

**Comment by mikeymike** [comment]
Hey @page-fault-in-nonpaged-area ... thank you for raising this issue and updating us as you progressed, this does still give us valuable insight. 

You can also make use of `paddle.PtrTo` function for those props that are not required but you want to set, which prevents you needing to create temporary variables.

In your case (latest example) it would look something like this... 

```
for idxPr, nxPrice := range nxProduct.Prices {
        price, err := s.Client.CreatePrice(ctx, &paddle.CreatePriceRequest{
	        ProductID: product.ID,
	        UnitPrice: paddle.Money{
		        Amount: strconv.Itoa(nxPrice.Price),
	        },
	        BillingCycle: &paddle.Duration{
		        Interval:  paddle.IntervalMonth,
		        Frequency: 1,
	        },
	        CustomData: map[string]interface{}{
		        "internal_id": nxPrice.InternalID,
	        },
	        TaxMode: paddle.PtrTo(paddle.TaxModeExternal),
        })
        if err != nil {
	        panic(err)
        }
```

Hope that helps !
