### ISSUE TITLE
[Bug]: No way to specify which subscription to resume

### ISSUE THREAD

**Issue by PaulSonOfLars** [PaddleHQ/paddle-go-sdk#4]
### What happened?

There seems to be no way to pass in a subscription_id to the ResumeSubscription method.

The associated `ResumeSubscriptionRequest` type simply doesn't specify it anywhere: https://github.com/PaddleHQ/paddle-go-sdk/blob/main/subscriptions.go#L953

### Steps to reproduce

1. Try to resume a subscription
2. Fail to find SubscriptionId field: https://github.com/PaddleHQ/paddle-go-sdk/blob/main/subscriptions.go#L953

### What did you expect to happen?

To have a SubscriptionID field

**Comment by mikeymike** [comment]
Hi @PaulSonOfLars, thank you for reporting this issue! 

This looks to be related to some of the generated code where a union is used, we'll take a look at this and get a release out ASAP 🙏

**Comment by PaulSonOfLars** [comment]
Np, sounds good! :) 

Great work otherwise - looking forward to moving away from my own libs over to this, will definitely make my life easier! And even better once webhooks are properly supported... 😄
