### ISSUE TITLE
[Bug]: POST method is used instead of PATCH for previewing subscription change

### ISSUE THREAD

**Issue by ribtoks** [PaddleHQ/paddle-go-sdk#8]
### What happened?

Call to `PreviewSubscription()` failed with an error `Decoding issue in call to POST /subscriptions/<redacted>/preview (HTTP status 405): found nil paddle.Error when one was expected`

### Steps to reproduce

There're no special steps to reproduce other than calling this method.

[This documentation](https://developer.paddle.com/api-reference/subscriptions/preview-subscription) says that method should be `PATCH` while [source code](https://github.com/PaddleHQ/paddle-go-sdk/blob/f80b5ef5e6cba53af7c6944d79c998d9ef47871c/subscriptions.go#L1069) does `POST`.

### What did you expect to happen?

API call succeeds or at least Paddle own parsing would not fail with that weird error.

**Comment by mikeymike** [comment]
Hey @ribtoks, thank you for raising this issue, I can confirm we consider this as a high priority and will be looking to get a fix for this as soon as possible.

**Comment by ribtoks** [comment]
Hey @mikeymike How is that high priority work going?

**Comment by mikeymike** [comment]
Hi @ribtoks I wanted to give you an update on this before the weekend as some blockers in the code generation prevented a release today. I'll update here again on Monday with progress details on this, apologies for the delay!

**Comment by mikeymike** [comment]
Hey @ribtoks this is now released in [v0.4.0](https://github.com/PaddleHQ/paddle-go-sdk/releases/tag/v0.4.0) 👍
